# 1 - Crie um array com os números de 0 a 9 , utilize somente 1 dimensão 


In [2]:
import numpy as np 
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


# 2 - Crie um array com os números de 0 a 9 como o exercicio anterior , mas utilize List Compreensions

In [1]:
import numpy as np 
array = np.array([i for i in range(0,10)])
print(array)

[0 1 2 3 4 5 6 7 8 9]


# 3 - Crie um array com os números de 0 a 8 utilize 2 dimensões , ou seja , com 3 linhas 
# (3x3)

In [3]:
import numpy as np 
array = np.arange(9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4 - Crie um array do tipo float , com 10 números de sua escolha , mas utilize 32 bits/ 4 bytes 

In [4]:
import numpy as np 
array = np.arange(0,9,dtype='f4')
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


# 5 - Crie um array com os números de 1 a 20 , escolhendo o tipo de dado que ocupara 
# o menor espaço da memoria. Em seguida imprima o quanto ele ocupou em bytes 


In [5]:
import numpy as np 
array = np.arange(1,21,dtype=np.int8)
print(array)
print(array.nbytes)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
20


# 6 - Crie uma matriz 2x2 e imprima o primeiro elemento da primeira linha , e o último elemento 
# da última linha.

In [8]:
import numpy as np 
array = np.random.randint(1,5,(2,2))
print(array)
print(array[0][0])
print(array[1][1])

[[4 1]
 [1 4]]
4
4


# 7 - Gere um array 3x3 com números inteiros aleatórios entre 5 a 20. Então imprima a primeira 
# a primeira coluna e última linha 

In [1]:
import numpy as np
array = np.random.randint(5,20,(3,3))
print(array)
print(array[:,0])
print(array[2,:])

[[17  8 14]
 [15 17 16]
 [18 16 19]]
[17 15 18]
[18 16 19]


# 8 - Crie uma matriz 3x3 aleatória.Percorra linha por linha com um laço e imprima 
# a soma de cada linha.

In [2]:
import numpy as np 
array = np.random.randint(1,50,(3,3))
for linha in array:
    print(np.sum(linha))

55
74
77


# 9 - Gere um array com os valores pares de 0 a 100 com list comprehension

In [3]:
import numpy as np 
array = np.array([i for i in range(0,101) if i % 2==0])
print(array)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# 10 - Crie um array 4x9 com valores quaisquer , redimensione para as dimensões 36 
# 

In [5]:
import numpy as np 
array = np.random.randint(0,10,(4,9))
print(array.reshape(36))
print(array.reshape(6,6))

[8 5 1 9 8 8 2 6 9 3 1 6 1 2 5 0 4 2 6 6 8 0 9 7 3 2 6 6 2 6 6 2 7 8 1 7]
[[8 5 1 9 8 8]
 [2 6 9 3 1 6]
 [1 2 5 0 4 2]
 [6 6 8 0 9 7]
 [3 2 6 6 2 6]
 [6 2 7 8 1 7]]


# 11 - Crie Uma função que receba três arrays de mesmo formato , então retorne elas 
# concatenadas em uma só. Se as matrizes recebidas não forem do mesmo formato gere uma exceção.

In [6]:
import numpy as np 

def combina(arr1,arr2,arr3):
    if arr1.shape !=arr2.shape or arr1.shape != arr3.shape:
        raise Exception("Formatos são diferentes")

    return np.concatenate((arr1,arr2,arr3))

array1 = np.array([1,2,3])
array2 = np.array([3,4,5])
array3 = np.array([6,7,8])

print(combina(array1,array2,array3))

[1 2 3 3 4 5 6 7 8]


# 12 - Crie uma função que divida um array em N pedaços , mas matenha 
# só os valores absolutos dos valores deste array.

In [7]:
import numpy as np 
def divide_abs(arr,n):
    arr = np.array_split(arr,n)
    arr = np.abs(arr)
    return arr 

array1 = np.array([1,2,3,-4,5,-7])
print(divide_abs(array1,3))


[[1 2]
 [3 4]
 [5 7]]


# 13 - Crie uma função que receba um array e retorne quantos números positivos 
# ela contém 

In [10]:
import numpy as np 

def conta_positivos(arr):
    return len(np.where(arr>0)[0])

array = np.array([1,2,3,4,5,-7])
print(conta_positivos(array))    

5


# 14 - Crie uma função que receba uma matriz e retorne os indices dos números que são divísiveis por 3 

In [11]:
import numpy as np 

def divisiveis_por_3(arr):
    return np.where(arr % 3 == 0)[0]

array = np.array([4,5,6,7,8,9])
print(divisiveis_por_3(array))    

[2 5]


# 15 - Crie uma função que diga se um array possui números negativos.

In [ ]:
import numpy as np 

def tem_negativo(arr):
    return np.arr(arr>0)

array = np.array([4,5,6,7,8,9])
print(tem_negativo(array))


: 

# 16 - Crie uma função que renova os números negativos de um array

# 17 -Crie uma função que receba um número inicial e final , e uma array . 
# A função deve retornar uma nova array somente com os números dentro deste intervalo.

# 18 - Crie uma função que ordene uma matriz e remova todos os números impares

In [3]:
import numpy as np

def ordena_pares(arr):
    arr = np.sort(arr)
    filter = arr % 2 == 1
    return arr[filter]

array = np.random.randint(0,10,(100))
print(array)

[3 7 1 4 9 7 3 5 1 9 4 8 3 3 1 1 5 2 6 6 2 5 2 6 3 5 5 7 4 7 0 6 9 2 5 3 3
 5 2 6 2 2 8 4 3 3 2 6 6 3 0 0 1 9 3 2 3 7 3 8 2 5 7 9 4 4 8 0 8 6 9 0 8 1
 2 0 0 2 6 9 4 1 4 1 3 8 0 9 2 5 2 2 7 0 1 2 5 5 9 0]


# 19 - Realize o mesmo exercicio anterior , mas remova valores duplicados.

In [4]:
import numpy as np

def ordena_pares_unicos(arr):
    arr = np.sort(arr)
    filter = arr % 2 == 1
    return np.unique(arr[filter])

array = np.random.randint(0,10,(100))
print(array)

[3 9 1 9 9 0 2 0 4 8 6 7 2 1 5 5 6 8 9 6 8 4 3 5 1 6 1 4 0 4 3 9 0 6 8 8 8
 4 4 7 0 3 6 5 6 9 4 9 7 5 0 5 6 7 2 4 3 3 7 9 7 9 4 0 1 8 9 2 8 6 5 0 7 4
 1 0 9 5 0 7 9 0 4 9 8 9 0 1 3 1 2 5 4 9 3 2 4 4 3 5]
