In [ ]:
import numpy as np 
boolean = np.bool_(True)
print(boolean,type(boolean))

: 

In [ ]:
import numpy as np 
string= np.string_("Este e um texto")
print(string,type(string))

In [ ]:
import numpy as np 
string= np.unicode_("Este é um texto")
print(string,type(string))

In [ ]:
import numpy as np 
inteiro = np.intc(-12)
uinteiro = np.uintc(102)
long= np.int_(89839399)
ulong = np.uint(345656)
print(inteiro,type(inteiro))
print(uinteiro,type(uinteiro))
print(long,type(long))
print(ulong,type(ulong))

In [ ]:
import numpy as np 
ponto_flutuante = np.float(1002.34)

ponto_flutuante_2 = np.float32(3994.34)
print(ponto_flutuante,type(ponto_flutuante))
print(ponto_flutuante_2,type(ponto_flutuante_2))

In [ ]:
import numpy as np 
int8 = np.int8(20)
int16 = np.int16(100)
uint8 = np.uint8(34)
uint16 = np.uint16(344)
print(int8,type(int8))
print(int16,type(int16))
print(uint8,type(uint8))
print(uint16,type(uint16))


In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)
print(type(array))
print(array.dtype)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,0],dtype=np.int8)
print(array)
print(type(array))
print(array.dtype)

In [ ]:
import numpy as np 
array = np.array(["1","234","1"],dtype=np.string_)
print(array)
print(type(array))
print(array.dtype)

In [ ]:
import numpy as np
class Pessoa:
    def __init__(self,nome,idade):
        self.nome = nome 
        self.idade = idade

array = np.array([Pessoa("Wallace",32),Pessoa("Maria",26)])
print(array)
print(type(array))
print(array.dtype,end="\n\n")

print(array[0].nome,array[1].idade)

In [ ]:
import numpy as np
tipo_pessoa = np.dtype([('nome','S10'),('Idade','i4')])

array = np.array([('Roger',33),('Ivan',45)])
print(array)

In [ ]:
import numpy as np 
array = np.array([1,2,3,45,6,7,8,9,0])
print(array)
print(array.ndim)
print(array.size)
print(len(array))
print(array.shape)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)


In [ ]:
import numpy as np 

array1 = np.zeros(9)
array2 = np.ones(3)
array3 = np.empty(6)
array4 = np.identity(4)

print(array1,end='\n\n')
print(array2,end='\n\n')
print(array3,end='\n\n')
print(array4,end='\n\n')


In [ ]:
import numpy as np 

array1 = np.arange(9)
array2 = np.arange(4,16)
print(array1)
print(array2)

In [ ]:
import numpy as np 
array = np.full((4,4),10)
print(array)

In [ ]:
import numpy as np 
array_float = np.random.rand(4,4)
array_int = np.random.randint(5,10)
print(array_float)
print(array_int)

In [ ]:
#List Comprehesion com numpy
import numpy as np 
array = np.array([ i for i in range(0,10)])
print(array)

In [ ]:
#List Comprehesion com numpy
import numpy as np 
array = np.array([
    [i for i in range(0,3)],
    [i for i in range(3,6)],
    [i for i in range(6,9)]],
)
print(array)

In [ ]:
def aprender():
    rows = []
    for i in range(0,10):
        rows.append(i)
        return rows
aprender()    

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array[2])


In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')

print(array[2])
print(array[2][2])
print(array[2,2])
print(array[1:3])

In [ ]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array,end='\n\n')
print(array[1,:])
print(array[:,2])

In [ ]:
import numpy as np 
array = np.array([1,2,3,4])
for i in array:
    print(i)

In [ ]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
for i in array:
    for j in array:
        print(j)

In [ ]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)

for x in np.nditer(array,order='F'):
    print(x)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
array[1,1:3] = [0,0]
print(array)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
print(array)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
print(array)
array[1,1:3] = [0,0]
print(array)
array[0,0] = 10
print(array)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[:,2] = [0,0,0]
print(array)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4])
array2 = np.append(array,[5,6,7,8,9])
print(array2)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')
array2 = np.append(array,[5,6,7,8,9])
print(array2)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')
array2 = np.append(array,[[10,11,12]],axis=0)
print(array2)

In [ ]:
import numpy as np 
array = np.array([1,2,3])
array2 = np.insert(array,1,10)
print(array2) 

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1 = np.insert(array,1,[3,3,3],axis=0)
print(array1)

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1 = np.delete(array,1,axis=0)
print(array1)

In [ ]:
import numpy as np 
array = np.array([1,2,3])
copy_array = array
copy_array[0] = 0
print(array)

In [ ]:
import numpy as np 
array = np.array([1,2,3])
copy_array = array.copy()
copy_array[0] = 0
print(array)

In [ ]:
def aprender(dados:str) -> str:
    return str(dados) 

aprender('ola') 

In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array = array.reshape(9)
print(array)

In [ ]:
import numpy as np 
array = np.array([i for i in range(0,27)])
print(array)
array = array.reshape(3,9)
print(array)

In [ ]:
import numpy as np 
array1 = np.array([1,2,3])
array2 = np.array([2,4,6])

print(array1 +array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

In [ ]:
import numpy as np 
array1 = np.array([10,20,30,5])
array2 = np.array([20,40,10,5])
array12 =np.concatenate((array1,array2),axis=0)
print(array12)

In [ ]:
import numpy as np 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[20,10,20],[20,40,50]])
array21 = np.concatenate((array1,array2),axis=0)
print(array21)

In [ ]:
import numpy as np 
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

arrayconc = np.vstack((array1,array2))
print(arrayconc)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6])
print(np.split(array,1))
print(np.split(array,2))

In [ ]:
import numpy as np 
array1 = np.array([[1,2,3,4],[4,5,6,7]])
print(np.split(array1,2))

In [ ]:
import numpy as np 
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(np.split(array1,2))

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6])
array1 = np.array_split(array,2)
array2 = np.array_split(array,3)
array3 = np.array_split(array,4)
print(array1)
print(array2)
print(array3)


In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6]])
array1 = np.array_split(array,2)
array2 = np.array_split(array,2)
array3 = np.array_split(array,2)
print(array1)
print(array2)
print(array3)


In [ ]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1 = np.hsplit(array,3)
print(array1)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5])
array_find = np.where(array >= 4)
print(array_find)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7])
array_find = np.where((array == 4) | (array == 7))
print(array_find)

In [ ]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,20,304,50,40])
array_find = np.where((array >0) & (array < 10))
print(array_find)

In [1]:
import numpy as np
array = np.array([1,0,1,1,1,0,2])
filtered_array = np.array([i for i in array if i ==0])
print(filtered_array)

[0 0]


In [2]:
import numpy as np 
array = np.array([4,1,3,2])
print(np.sort(array,kind='quicksort'))


[1 2 3 4]


In [3]:
import numpy as np 
array = np.array([[38,2,0],[5,6,7]])
print(np.sort(array,axis=0))
print(np.sort(array,axis=1))

[[ 5  2  0]
 [38  6  7]]
[[ 0  2 38]
 [ 5  6  7]]


In [5]:
import numpy as np 
arr1 = np.array([1,2,3,4,5,6,33])
arr2 = np.array([1,2,3,4,5,6,40])

array1 = np.add(arr1,arr2)
array2 = np.subtract(arr1,arr2)
array3 = np.multiply(arr1,arr2)
array4 = np.divide(arr1,arr2)

print(array1)
print(array2)
print(array3)
print(array4)



[ 2  4  6  8 10 12 73]
[ 0  0  0  0  0  0 -7]
[   1    4    9   16   25   36 1320]
[1.    1.    1.    1.    1.    1.    0.825]


In [9]:
import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

array1 = np.divide(arr1,arr2)
array2 = np.floor_divide(arr1,arr2)

print(array1)
print(array2)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

array1 = np.power(arr1,arr2)
print(array1)

[[        1         4        27]
 [      256      3125     46656]
 [   823543  16777216 387420489]]


In [11]:
import numpy as np 
arr1 = np.array([2,2,100])
arr2 = np.array([2,3,31])

array1 = np.mod(arr1,arr2)
print(array1)

[0 2 7]


In [12]:
import numpy as np 
arr1 = np.array([2,2,100])
arr2 = np.array([2,3,31])

array1 = np.divmod(arr1,arr2)
print(array1)

(array([1, 0, 3]), array([0, 2, 7]))


In [13]:
import numpy as np 
arr1 = np.array([4,25,100])

array1 = np.sqrt(arr1)
print(array1)

[ 2.  5. 10.]


In [15]:
import numpy as np 

arr1 = np.array([3.14159,2.71])
array1 = np.around(arr1,2)
print(array1)

[3.14 2.71]
