In [2]:
import numpy as np 
boolean = np.bool_(True)
print(boolean,type(boolean))

True <class 'numpy.bool_'>


In [4]:
import numpy as np 
string= np.string_("Este e um texto")
print(string,type(string))

b'Este e um texto' <class 'numpy.bytes_'>


In [5]:
import numpy as np 
string= np.unicode_("Este é um texto")
print(string,type(string))

Este é um texto <class 'numpy.str_'>


In [6]:
import numpy as np 
inteiro = np.intc(-12)
uinteiro = np.uintc(102)
long= np.int_(89839399)
ulong = np.uint(345656)
print(inteiro,type(inteiro))
print(uinteiro,type(uinteiro))
print(long,type(long))
print(ulong,type(ulong))

-12 <class 'numpy.intc'>
102 <class 'numpy.uintc'>
89839399 <class 'numpy.int32'>
345656 <class 'numpy.uint32'>


In [1]:
import numpy as np 
ponto_flutuante = np.float(1002.34)

ponto_flutuante_2 = np.float32(3994.34)
print(ponto_flutuante,type(ponto_flutuante))
print(ponto_flutuante_2,type(ponto_flutuante_2))

1002.34 <class 'float'>
3994.34 <class 'numpy.float32'>


C:\Users\walla\AppData\Local\Temp\ipykernel_56400\247381712.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  ponto_flutuante = np.float(1002.34)


In [2]:
import numpy as np 
int8 = np.int8(20)
int16 = np.int16(100)
uint8 = np.uint8(34)
uint16 = np.uint16(344)
print(int8,type(int8))
print(int16,type(int16))
print(uint8,type(uint8))
print(uint16,type(uint16))


20 <class 'numpy.int8'>
100 <class 'numpy.int16'>
34 <class 'numpy.uint8'>
344 <class 'numpy.uint16'>


In [7]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int32


In [8]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,0],dtype=np.int8)
print(array)
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int8


In [9]:
import numpy as np 
array = np.array(["1","234","1"],dtype=np.string_)
print(array)
print(type(array))
print(array.dtype)

[b'1' b'234' b'1']
<class 'numpy.ndarray'>
|S3


In [1]:
import numpy as np
class Pessoa:
    def __init__(self,nome,idade):
        self.nome = nome 
        self.idade = idade

array = np.array([Pessoa("Wallace",32),Pessoa("Maria",26)])
print(array)
print(type(array))
print(array.dtype,end="\n\n")

print(array[0].nome,array[1].idade)

<class 'numpy.ndarray'>
object

Wallace 26


In [2]:
import numpy as np
tipo_pessoa = np.dtype([('nome','S10'),('Idade','i4')])

array = np.array([('Roger',33),('Ivan',45)])
print(array)

[['Roger' '33']
 ['Ivan' '45']]


In [1]:
import numpy as np 
array = np.array([1,2,3,45,6,7,8,9,0])
print(array)
print(array.ndim)
print(array.size)
print(len(array))
print(array.shape)
print(array.dtype)
print(array.itemsize)
print(array.nbytes)


[ 1  2  3 45  6  7  8  9  0]
1
9
9
(9,)
int32
4
36


In [2]:
import numpy as np 

array1 = np.zeros(9)
array2 = np.ones(3)
array3 = np.empty(6)
array4 = np.identity(4)

print(array1,end='\n\n')
print(array2,end='\n\n')
print(array3,end='\n\n')
print(array4,end='\n\n')


[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1.]

[1.e-323 0.e+000 0.e+000 0.e+000 0.e+000 0.e+000]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [3]:
import numpy as np 

array1 = np.arange(9)
array2 = np.arange(4,16)
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8]
[ 4  5  6  7  8  9 10 11 12 13 14 15]


In [4]:
import numpy as np 
array = np.full((4,4),10)
print(array)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [5]:
import numpy as np 
array_float = np.random.rand(4,4)
array_int = np.random.randint(5,10)
print(array_float)
print(array_int)

[[0.15075362 0.85225149 0.5056621  0.51582812]
 [0.96941267 0.80791725 0.17283248 0.9441176 ]
 [0.03689792 0.01438238 0.05775187 0.5971397 ]
 [0.46017742 0.66225486 0.26423557 0.24626125]]
5


In [ ]:
#List Comprehesion com numpy
import numpy as np 
array = np.array([ i for i in range(0,10)])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#List Comprehesion com numpy
import numpy as np 
array = np.array([
    [i for i in range(0,3)],
    [i for i in range(3,6)],
    [i for i in range(6,9)]],
)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1]:
def aprender():
    rows = []
    for i in range(0,10):
        rows.append(i)
        return rows
aprender()    

[0]

In [2]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array[2])


3


In [5]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')

print(array[2])
print(array[2][2])
print(array[2,2])
print(array[1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]
9
9
[[4 5 6]
 [7 8 9]]


In [7]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array,end='\n\n')
print(array[1,:])
print(array[:,2])

[[1 2 3 4]
 [5 6 7 8]]

[5 6 7 8]
[3 7]


In [8]:
import numpy as np 
array = np.array([1,2,3,4])
for i in array:
    print(i)

1
2
3
4


In [10]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
for i in array:
    for j in array:
        print(j)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4]
[5 6 7 8]


In [12]:
import numpy as np 
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array)

for x in np.nditer(array,order='F'):
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
1
5
2
6
3
7
4
8


In [15]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
array[1,1:3] = [0,0]
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 4]
 [4 0 0]
 [7 8 9]]


In [17]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 4]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[0] = [1,2,4]
print(array)
array[1,1:3] = [0,0]
print(array)
array[0,0] = 10
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 4]
 [4 5 6]
 [7 8 9]]
[[1 2 4]
 [4 0 0]
 [7 8 9]]
[[10  2  4]
 [ 4  0  0]
 [ 7  8  9]]


In [6]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
array[:,2] = [0,0,0]
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 0]
 [4 5 0]
 [7 8 0]]


In [7]:
import numpy as np 
array = np.array([1,2,3,4])
array2 = np.append(array,[5,6,7,8,9])
print(array2)

[1 2 3 4 5 6 7 8 9]


In [8]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')
array2 = np.append(array,[5,6,7,8,9])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9 5 6 7 8 9]


In [9]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array,end='\n\n')
array2 = np.append(array,[[10,11,12]],axis=0)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
import numpy as np 
array = np.array([1,2,3])
array2 = np.insert(array,1,10)
print(array2) 

[ 1 10  2  3]


In [12]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1 = np.insert(array,1,[3,3,3],axis=0)
print(array1)

[[1 2 3]
 [3 3 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array1 = np.delete(array,1,axis=0)
print(array1)

[[1 2 3]
 [7 8 9]]


In [1]:
import numpy as np 
array = np.array([1,2,3])
copy_array = array
copy_array[0] = 0
print(array)

[0 2 3]


In [2]:
import numpy as np 
array = np.array([1,2,3])
copy_array = array.copy()
copy_array[0] = 0
print(array)

[1 2 3]


In [3]:
def aprender(dados:str) -> str:
    return str(dados) 

aprender('ola') 

'ola'